elasticsearch:
  host: "https://elasticsearch.srv.webis.de"
  port: 9200
  user: "po87xox"
  index: "corpus_mastodon_statuses_*"
  language: "en"
  instances_file: "data/instances.txt"

date_range:
  after: "2024-01-01T00:00:00"
  before: "2024-12-31T23:59:59"
  
dir:
  output_dir: "/mnt/ceph/storage/data-in-progress/data-teaching/theses/thesis-klueber/output_data/"
  input_dir: "/mnt/ceph/storage/data-in-progress/data-teaching/theses/thesis-klueber/input_data/"
  input_sample_dir: "/mnt/ceph/storage/data-in-progress/data-teaching/theses/thesis-klueber/input_data_sample/"
  lsh_dir: "/mnt/ceph/storage/data-in-progress/data-teaching/theses/thesis-klueber/lsh/"
  deduplication_dir: "/mnt/ceph/storage/data-in-progress/data-teaching/theses/thesis-klueber/deduplicated_data/"
  toxicity_analysis_dir: "/mnt/ceph/storage/data-in-progress/data-teaching/theses/thesis-klueber/toxicity_data/"
  merge_dir: "/mnt/ceph/storage/data-in-progress/data-teaching/theses/thesis-klueber/output_data/"